### ISSUE TITLE
[Event Tracking] Add event tracking

### ISSUE THREAD

**Issue by lmcmz** [Outblock/FRW-Android#316]
Doc
https://app.gitbook.com/o/btnrCjBfFA1CijnAHf9d/s/uD5IIQEzBNOcwceEz9qr/

**Comment by Peppermint1020** [comment]
- [ ] Super event
- [ ] Identify User
- [ ] Script Error
- [ ] Delegation Created
- [ ] On Ramp Clicked
- [ ] COA Creation
- [ ] Security Tool
- [ ] Multi-Backup Created
- [ ] Multi-Backup Creation Failed
- [ ] Cadence Transaction Signed
- [ ] EVM Transaction Signed
- [ ] FT Transfer
- [ ] NFT Transfer
- [ ] Transaction Result
- [ ] Account Created
- [ ] Account Recovered
- [ ] Account Creation Time
- [ ] No Timing Events

**Comment by Peppermint1020** [comment]
Tested on Android 200 (i1.6.20).
(1)Script_error is triggered incorrectly when switch accounts.
(2)Delegation Created not triggered

**Comment by Peppermint1020** [comment]
Already released in Android r2.6.3

**Comment by Peppermint1020** [comment]
Close from now. Need improve in script error triggering
